Nop.Plugin.Payments.CyberSource/Controllers/CyberSourceController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Plugin.Payments.CyberSource.Domain;
using Nop.Plugin.Payments.CyberSource.Models;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.ScheduleTasks;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Payments.CyberSource.Controllers
{
    [Area(AreaNames.Admin)]
    [AuthorizeAdmin]
    [AutoValidateAntiforgeryToken]
    public class CyberSourceController : BasePluginController
    {
        #region Fields

        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly IScheduleTaskService _scheduleTaskService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;

        #endregion

        #region Ctor

        public CyberSourceController(ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            IScheduleTaskService scheduleTaskService,
            ISettingService settingService,
            IStoreContext storeContext)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _scheduleTaskService = scheduleTaskService;
            _settingService = settingService;
            _storeContext = storeContext;
        }

        #endregion

        #region Methods

        public async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            var storeId = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var settings = await _settingService.LoadSettingAsync<CyberSourceSettings>(storeId);

            var model = new ConfigurationModel
            {
                UseSandbox = settings.UseSandbox,
                MerchantId = settings.MerchantId,
                KeyId = settings.KeyId,
                SecretKey = settings.SecretKey,
                TokenizationEnabled = settings.TokenizationEnabled,
                PaymentConnectionMethodId = (int)settings.PaymentConnectionMethod,
                PayerAuthenticationEnabled = settings.PayerAuthenticationEnabled,
                PayerAuthenticationRequired = settings.PayerAuthenticationRequired,
                TransactionTypeId = (int)settings.TransactionType,
                CvvRequired = settings.CvvRequired,
                AvsActionTypeId = (int)settings.AvsActionType,
                CvnActionTypeId = (int)settings.CvnActionType,
                DecisionManagerEnabled = settings.DecisionManagerEnabled,
                ConversionDetailReportingEnabled = settings.ConversionDetailReportingEnabled,
                ConversionDetailReportingFrequency = settings.ConversionDetailReportingFrequency,
                ActiveStoreScopeConfiguration = storeId
            };

            if (storeId > 0)
            {
                model.UseSandbox_OverrideForStore = await _settingService.SettingExistsAsync(settings, setting => setting.UseSandbox, storeId);
                model.MerchantId_OverrideForStore = await _settingService.SettingExistsAsync(settings, setting => setting.MerchantId, storeId);
                model.KeyId_OverrideForStore = await _settingService.SettingExistsAsync(settings, setting => setting.KeyId, storeId);
                model.SecretKey_OverrideForStore = await _settingService.SettingExistsAsync(settings, setting => setting.SecretKey, storeId);
                model.TokenizationEnabled_OverrideForStore = await _settingService.SettingExistsAsync(settings, setting => setting.TokenizationEnabled, storeId);
                model.PaymentConnectionMethodId_OverrideForStore = await _settingService.SettingExistsAsync(settings, setting => setting.PaymentConnectionMethod, storeId);
                model.PayerAuthenticationEnabled_OverrideForStore = await _settingService.SettingExistsAsync(settings, setting => setting.PayerAuthenticationEnabled, storeId);
                model.PayerAuthenticationRequired_OverrideForStore = await _settingService.SettingExistsAsync(settings, setting => setting.PayerAuthenticationRequired, storeId);
                model.TransactionTypeId_OverrideForStore = await _settingService.SettingExistsAsync(settings, setting => setting.TransactionType, storeId);
                model.CvvRequired_OverrideForStore = await _settingService.SettingExistsAsync(settings, setting => setting.CvvRequired, storeId);
                model.AvsActionTypeId_OverrideForStore = await _settingService.SettingExistsAsync(settings, setting => setting.AvsActionType, storeId);
                model.CvnActionTypeId_OverrideForStore = await _settingService.SettingExistsAsync(settings, setting => setting.CvnActionType, storeId);
                model.DecisionManagerEnabled_OverrideForStore = await _settingService.SettingExistsAsync(settings, setting => setting.DecisionManagerEnabled, storeId);
            }

            var scheduleTask = await _scheduleTaskService.GetTaskByTypeAsync(CyberSourceDefaults.OrderStatusUpdateTask);
            if (scheduleTask is not null)
            {
                model.ConversionDetailReportingEnabled = scheduleTask.Enabled;
                model.ConversionDetailReportingFrequency = scheduleTask.Seconds / 60;
            }

            return View("~/Plugins/Payments.CyberSource/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return await Configure();

            var storeId = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var settings = await _settingService.LoadSettingAsync<CyberSourceSettings>(storeId);

            settings.UseSandbox = model.UseSandbox;
            settings.MerchantId = model.MerchantId;
            settings.KeyId = model.KeyId;
            settings.SecretKey = model.SecretKey;
            settings.TokenizationEnabled = model.TokenizationEnabled;
            settings.PaymentConnectionMethod = (ConnectionMethodType)model.PaymentConnectionMethodId;
            settings.PayerAuthenticationEnabled = model.PayerAuthenticationEnabled;
            settings.PayerAuthenticationRequired = model.PayerAuthenticationRequired;
            settings.TransactionType = (TransactionType)model.TransactionTypeId;
            settings.CvvRequired = model.CvvRequired;
            settings.AvsActionType = (AvsActionType)model.AvsActionTypeId;
            settings.CvnActionType = (CvnActionType)model.CvnActionTypeId;
            settings.DecisionManagerEnabled = model.DecisionManagerEnabled;
            settings.ConversionDetailReportingEnabled = model.ConversionDetailReportingEnabled;
            settings.ConversionDetailReportingFrequency = model.ConversionDetailReportingFrequency;

            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.UseSandbox, model.UseSandbox_OverrideForStore, storeId, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.MerchantId, model.MerchantId_OverrideForStore, storeId, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.KeyId, model.KeyId_OverrideForStore, storeId, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.SecretKey, model.SecretKey_OverrideForStore, storeId, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.TokenizationEnabled, model.TokenizationEnabled_OverrideForStore, storeId, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.PaymentConnectionMethod, model.PaymentConnectionMethodId_OverrideForStore, storeId, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.PayerAuthenticationEnabled, model.PayerAuthenticationEnabled_OverrideForStore, storeId, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.PayerAuthenticationRequired, model.PayerAuthenticationRequired_OverrideForStore, storeId, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.TransactionType, model.TransactionTypeId_OverrideForStore, storeId, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.CvvRequired, model.CvvRequired_OverrideForStore, storeId, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.AvsActionType, model.AvsActionTypeId_OverrideForStore, storeId, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.CvnActionType, model.CvnActionTypeId_OverrideForStore, storeId, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.DecisionManagerEnabled, model.DecisionManagerEnabled_OverrideForStore, storeId, false);
            await _settingService.SaveSettingAsync(settings, setting => setting.ConversionDetailReportingEnabled, 0, false);

Nop.Plugin.Payments.CyberSource/Views/Configure.cshtml
@model ConfigurationModel

@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="CyberSource" asp-action="Configure" method="post">
    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">
                <p>
                    To enable this payment method, you'll need to:<br />
                    <br />
                    1. <a href="https://ebc2.cybersource.com/ebc2/registration/external" target="_blank">Sign-up for CyberSource account</a><br />
                    2. Go to <b>Payment Configuration</b> → <b>Key Management</b>. Generate key with type <b>REST - Shared Secret</b><br />
                    3. Fill in your account details below<br />
                </p>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UseSandbox_OverrideForStore" asp-input="UseSandbox" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UseSandbox" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseSandbox" />
                        <span asp-validation-for="UseSandbox"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="MerchantId_OverrideForStore" asp-input="MerchantId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="MerchantId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="MerchantId" asp-required="true" />
                        <span asp-validation-for="MerchantId"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="KeyId_OverrideForStore" asp-input="KeyId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="KeyId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="KeyId" asp-required="true" />
                        <span asp-validation-for="KeyId"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="SecretKey_OverrideForStore" asp-input="SecretKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="SecretKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="SecretKey" asp-required="true" html-attributes="@(new { value = Model.SecretKey })" />
                        <span asp-validation-for="SecretKey"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="TokenizationEnabled_OverrideForStore" asp-input="TokenizationEnabled" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="TokenizationEnabled" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="TokenizationEnabled" />
                        <span asp-validation-for="TokenizationEnabled"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="PaymentConnectionMethodId_OverrideForStore" asp-input="PaymentConnectionMethodId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="PaymentConnectionMethodId" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="PaymentConnectionMethodId" asp-items="@await (((ConnectionMethodType)Model.PaymentConnectionMethodId).ToSelectListAsync())" />
                        <span asp-validation-for="PaymentConnectionMethodId"></span>
                    </div>
                </div>
                <div class="form-group row" id="payer-authentication">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="PayerAuthenticationEnabled_OverrideForStore" asp-input="PayerAuthenticationEnabled" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="PayerAuthenticationEnabled" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PayerAuthenticationEnabled" />
                        <span asp-validation-for="PayerAuthenticationEnabled"></span>
                    </div>
                </div>
                <nop-nested-setting asp-for="PayerAuthenticationEnabled">
                    <div class="form-group row" id="payer-authentication-force">
                        <div class="col-md-3">
                            <nop-override-store-checkbox asp-for="PayerAuthenticationRequired_OverrideForStore" asp-input="PayerAuthenticationRequired" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                            <nop-label asp-for="PayerAuthenticationRequired" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="PayerAuthenticationRequired" />
                            <span asp-validation-for="PayerAuthenticationRequired"></span>
                        </div>
                    </div>
                </nop-nested-setting>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="TransactionTypeId_OverrideForStore" asp-input="TransactionTypeId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="TransactionTypeId" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="TransactionTypeId" asp-items="@await (((TransactionType)Model.TransactionTypeId).ToSelectListAsync())" />
                        <span asp-validation-for="TransactionTypeId"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="CvvRequired_OverrideForStore" asp-input="CvvRequired" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="CvvRequired" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="CvvRequired" />
                        <span asp-validation-for="CvvRequired"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AvsActionTypeId_OverrideForStore" asp-input="AvsActionTypeId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AvsActionTypeId" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="AvsActionTypeId" asp-items="@await (((AvsActionType)Model.AvsActionTypeId).ToSelectListAsync())" />
                        <span asp-validation-for="AvsActionTypeId"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="CvnActionTypeId_OverrideForStore" asp-input="CvnActionTypeId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="CvnActionTypeId" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="CvnActionTypeId" asp-items="@await (((CvnActionType)Model.CvnActionTypeId).ToSelectListAsync())" />
                        <span asp-validation-for="CvnActionTypeId"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="DecisionManagerEnabled_OverrideForStore" asp-input="DecisionManagerEnabled" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="DecisionManagerEnabled" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="DecisionManagerEnabled" />
                        <span asp-validation-for="DecisionManagerEnabled"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="ConversionDetailReportingEnabled" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="ConversionDetailReportingEnabled" />
                        <span asp-validation-for="ConversionDetailReportingEnabled"></span>
                    </div>
                </div>
                <nop-nested-setting asp-for="ConversionDetailReportingEnabled">
                    <div class="form-group row">
                        <div class="col-md-3">
                            <nop-label asp-for="ConversionDetailReportingFrequency" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="ConversionDetailReportingFrequency" />
                            <span asp-validation-for="ConversionDetailReportingFrequency"></span>
                        </div>
                    </div>
                </nop-nested-setting>
                <div class="form-group row">
                    <div class="col-md-9 offset-md-3">
                        <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<script asp-location="Footer">
    $(document).ready(function() {
        $('#@Html.IdFor(model => model.PaymentConnectionMethodId)').change(toggleConnectionMethod);
        toggleConnectionMethod();
    });

    function toggleConnectionMethod() {
        var flexMicroform = '@((int)ConnectionMethodType.FlexMicroForm)';
        var selectedMethodId = $('#@Html.IdFor(model => model.PaymentConnectionMethodId)').val();
        if (selectedMethodId && selectedMethodId == flexMicroform) {
            $('#payer-authentication').showElement();
            $('#payer-authentication-force').showElement();
        } else {
            $('#payer-authentication').hideElement();
            $('#payer-authentication-force').hideElement();
        }
    }
</script>

Nop.Plugin.Payments.CyberSource/Views/PayerAuthentication.cshtml
<link rel="stylesheet" href="~/Plugins/Payments.CyberSource/Content/css/modal.css" />
<script asp-location="Footer" src="~/lib_npm/bootstrap/js/bootstrap.bundle.min.js"></script>

@* Device Data Collection form *@
<form id="cardinal-collection-form" method="POST" target="collection-iframe" action="">
    <input id="cardinal-collection-form-input" type="hidden" name="JWT" value="">
</form>

<iframe id="cardinal-collection-iframe" name="collection-iframe" height="1" width="1" style="display: none;"></iframe>

@* Consumer Authentication form *@
<form id="step-up-form" target="step-up-iframe" method="post" action="">
    <input id="step-up-form-input" type="hidden" name="JWT" value="" />
</form>

<div id="step-up-modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@T("Plugins.Payments.CyberSource.PayerAuthentication.Title")</h5>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col">
                            <iframe id="step-up-iframe" name="step-up-iframe" style="border: none; margin-left: auto; margin-right: auto; display: block" height="800px" width="400px"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>