Nop.Plugin.Payments.CyberSource/Controllers/CyberSourceCustomerTokenController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Plugin.Payments.CyberSource.Domain;
using Nop.Plugin.Payments.CyberSource.Models;
using Nop.Plugin.Payments.CyberSource.Services;
using Nop.Plugin.Payments.CyberSource.Services.Helpers;
using Nop.Services.Customers;
using Nop.Web.Controllers;

namespace Nop.Plugin.Payments.CyberSource.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class CyberSourceCustomerTokenController : BasePublicController
    {
        #region Fields

        private readonly CustomerTokenService _customerTokenService;
        private readonly CyberSourceService _cyberSourceService;
        private readonly CyberSourceSettings _cyberSourceSettings;
        private readonly ICustomerService _customerService;
        private readonly IWorkContext _workContext;

        #endregion

        #region Ctor

        public CyberSourceCustomerTokenController(CustomerTokenService customerTokenService,
            CyberSourceService cyberSourceService,
            CyberSourceSettings cyberSourceSettings,
            ICustomerService customerService,
            IWorkContext workContext)
        {
            _customerTokenService = customerTokenService;
            _cyberSourceService = cyberSourceService;
            _cyberSourceSettings = cyberSourceSettings;
            _customerService = customerService;
            _workContext = workContext;
        }

        #endregion

        #region Methods

        public async Task<IActionResult> CustomerTokens()
        {
            var customer = await _workContext.GetCurrentCustomerAsync();
            if (!await _customerService.IsRegisteredAsync(customer))
                return Challenge();

            if (!CyberSourceService.IsConfigured(_cyberSourceSettings))
                return RedirectToRoute("CustomerInfo");

            if (!_cyberSourceSettings.TokenizationEnabled)
                return RedirectToRoute("CustomerInfo");

            var model = new CustomerTokenListModel();
            var tokens = await _customerTokenService.GetAllTokensAsync(customerId: customer.Id);
            foreach (var token in tokens)
            {
                var tokenModel = new CustomerTokenListModel.CustomerTokenDetailsModel
                {
                    ThreeDigitCardType = token.ThreeDigitCardType,
                    CardExpirationMonth = token.CardExpirationMonth,
                    CardExpirationYear = token.CardExpirationYear,
                    CardNumber = (token.FirstSixDigitOfCard ?? "XXXXXX") + "XXXXXX" + (token.LastFourDigitOfCard ?? "XXXX"),
                    Id = token.Id
                };

                model.Tokens.Add(tokenModel);
            }

            return View("~/Plugins/Payments.CyberSource/Views/CustomerToken/CustomerTokens.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> TokenDelete(int tokenId)
        {
            var customer = await _workContext.GetCurrentCustomerAsync();
            if (!await _customerService.IsRegisteredAsync(customer))
                return Challenge();

            //find token (ensure that it belongs to the current customer)
            var token = await _customerTokenService.GetByIdAsync(tokenId);
            if (token != null && token.CustomerId == customer.Id)
            {
                var (_, error) = await _cyberSourceService.DeletePaymentInstrumentAsync(token.SubscriptionId);
                if (!string.IsNullOrEmpty(error))
                    throw new NopException(error);

                await _customerTokenService.DeleteAsync(token);
            }

            //redirect to the token list page
            return Json(new
            {
                redirect = Url.RouteUrl(CyberSourceDefaults.CustomerTokensRouteName)
            });
        }

        public async Task<IActionResult> TokenAdd()
        {
            var customer = await _workContext.GetCurrentCustomerAsync();
            if (!await _customerService.IsRegisteredAsync(customer))
                return Challenge();

            if (!CyberSourceService.IsConfigured(_cyberSourceSettings))
                return RedirectToRoute("CustomerInfo");

            if (!_cyberSourceSettings.TokenizationEnabled)
                return RedirectToRoute("CustomerInfo");

            var model = new CustomerTokenEditModel();

            //years
            for (var i = 0; i < 15; i++)
            {
                var year = (DateTime.Now.Year + i).ToString();
                model.CustomerToken.ExpireYears.Add(new SelectListItem { Text = year, Value = year, });
            }

            //months
            for (var i = 1; i <= 12; i++)
            {
                model.CustomerToken.ExpireMonths.Add(new SelectListItem { Text = i.ToString("D2"), Value = i.ToString(), });
            }

            return View("~/Plugins/Payments.CyberSource/Views/CustomerToken/TokenAdd.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> TokenAdd(CustomerTokenEditModel model)
        {
            var customer = await _workContext.GetCurrentCustomerAsync();
            if (!await _customerService.IsRegisteredAsync(customer))
                return Challenge();

            if (ModelState.IsValid)
            {
                var cardNumber = CreditCardHelper.RemoveSpecialCharacters(model.CustomerToken.CardNumber);
                var firstSixDigitsOfCard = CreditCardHelper.GetFirstSixDigitsOfCard(cardNumber);
                var lastFourDigitsOfCard = CreditCardHelper.GetLastFourDigitsOfCard(cardNumber);
                var existingTokens = await _customerTokenService.GetAllTokensAsync(customer.Id);
                if (existingTokens.Any(token => token.FirstSixDigitOfCard == firstSixDigitsOfCard && token.LastFourDigitOfCard == lastFourDigitsOfCard))
                    throw new NopException("Token already exists!");

                var (instrumentResult, instrumentError) = await _cyberSourceService.CreateInstrumentIdAsync(cardNumber);
                if (!string.IsNullOrEmpty(instrumentError))
                    throw new NopException(instrumentError);

                var instrumentToken = instrumentResult?.Id;
                if (!string.IsNullOrEmpty(instrumentToken))
                {
                    var (paymentInstrumentResult, paymentInstrumentError) = await _cyberSourceService.CreatePaymentInstrumentAsync(
                        instrumentIdentifier: instrumentToken,
                        cardExpirationMonth: model.CustomerToken.ExpireMonth.PadLeft(2, '0'),
                        cardExpirationYear: model.CustomerToken.ExpireYear,
                        cardType: CreditCardHelper.GetCardTypeByNumber(cardNumber));

                    if (!string.IsNullOrEmpty(paymentInstrumentError))
                        throw new NopException(paymentInstrumentError);

                    if (paymentInstrumentResult != null)
                    {
                        await _customerTokenService.InsertAsync(new CyberSourceCustomerToken
                        {
                            CustomerId = customer.Id,
                            ThreeDigitCardType = CreditCardHelper.GetThreeDigitCardTypeByNumber(model.CustomerToken.CardNumber),
                            CardExpirationMonth = paymentInstrumentResult.Card?.ExpirationMonth,
                            CardExpirationYear = paymentInstrumentResult.Card?.ExpirationYear,
                            FirstSixDigitOfCard = firstSixDigitsOfCard,
                            LastFourDigitOfCard = lastFourDigitsOfCard,
                            InstrumentIdentifier = instrumentToken,
                            InstrumentIdentifierStatus = instrumentResult.State,
                            SubscriptionId = paymentInstrumentResult.Id
                        });
                    }
                }

                return RedirectToRoute(CyberSourceDefaults.CustomerTokensRouteName);
            }

            //years
            for (var i = 0; i < 15; i++)
            {
                var year = (DateTime.Now.Year + i).ToString();
                model.CustomerToken.ExpireYears.Add(new SelectListItem { Text = year, Value = year, });
            }

            //months
            for (var i = 1; i <= 12; i++)
            {
                model.CustomerToken.ExpireMonths.Add(new SelectListItem { Text = i.ToString("D2"), Value = i.ToString(), });
            }

            return View("~/Plugins/Payments.CyberSource/Views/CustomerToken/TokenAdd.cshtml", model);
        }

        public async Task<IActionResult> TokenEdit(int tokenId)
        {
            var customer = await _workContext.GetCurrentCustomerAsync();
            if (!await _customerService.IsRegisteredAsync(customer))
                return Challenge();

            if (!CyberSourceService.IsConfigured(_cyberSourceSettings))
                return RedirectToRoute("CustomerInfo");

            if (!_cyberSourceSettings.TokenizationEnabled)
                return RedirectToRoute("CustomerInfo");

            //find token (ensure that it belongs to the current customer)
            var token = await _customerTokenService.GetByIdAsync(tokenId);
            if (token == null || token.CustomerId != customer.Id)
                return RedirectToRoute(CyberSourceDefaults.CustomerTokensRouteName);

            var model = new CustomerTokenEditModel();

            //years
            for (var i = 0; i < 15; i++)
            {
                var year = (DateTime.Now.Year + i).ToString();
                model.CustomerToken.ExpireYears.Add(new SelectListItem { Text = year, Value = year, });
            }

            //months
            for (var i = 1; i <= 12; i++)
            {
                model.CustomerToken.ExpireMonths.Add(new SelectListItem { Text = i.ToString("D2"), Value = i.ToString(), });

Nop.Plugin.Payments.CyberSource/Views/CustomerToken/CustomerTokens.cshtml
@model CustomerTokenListModel

@{
    Layout = "_ColumnsTwo";
    NopHtml.AddTitleParts(T("Plugins.Payments.CyberSource.PaymentTokens").Text);
    NopHtml.AppendPageCssClassParts("html-account-page");
}

@section left
{
    @(await Component.InvokeAsync("CustomerNavigation", new { selectedTabId = CyberSourceDefaults.CustomerTokensMenuTab }))
}

<div class="page account-page order-list-page">
    <div class="page-title">
        <h1>@T("Account.MyAccount") - @T("Plugins.Payments.CyberSource.PaymentTokens")</h1>
    </div>
    <div class="page-body">
        @if (Model.Tokens.Any())
        {
            <div class="order-list">
                @foreach (var token in Model.Tokens)
                {
                    <div class="section order-item">
                        <div class="title">
                            <strong>@T("Payment.CardNumber"): @token.CardNumber</strong>
                        </div>
                        <ul class="info">
                            <li>@T("Payment.ExpirationDate"): <span class="order-date">@token.CardExpirationMonth / @token.CardExpirationYear</span></li>
                        </ul>
                        <div class="buttons">
                            <button type="button" class="button-2 edit-address-button" onclick="location.href = '@(Url.RouteUrl(CyberSourceDefaults.CustomerTokenEditRouteName, new {tokenId = token.Id}))'">@T("Common.Edit")</button>

                            <button type="button" class="button-2 delete-address-button" onclick="deletecybersourcetoken(@(token.Id))">@T("Common.Delete")</button>
                        </div>
                    </div>
                }
            </div>
            <script asp-location="Footer">
                function deletecybersourcetoken(tokenId) {
                    if (confirm('@T("Common.AreYouSure")')) {
                        var postData = {
                            tokenId: tokenId
                        };
                        addAntiForgeryToken(postData);

                        $.ajax({
                            cache: false,
                            type: 'POST',
                            url: '@Url.Action("TokenDelete", "CyberSourceCustomerToken")',
                            data: postData,
                            dataType: 'json',
                            success: function (data, textStatus, jqXHR) {
                                location.href = data.redirect;
                            },
                            error: function (jqXHR, textStatus, errorThrown) {
                                alert('Failed to delete');
                            }
                        });
                    }
                }
            </script>
        }
        else
        {
            <div class="no-data">
                @T("Plugins.Payments.CyberSource.PaymentTokens.NoTokens")
            </div>
        }
        <div class="add-button">
            <button type="button" class="button-1 add-address-button" onclick="location.href='@Url.RouteUrl(CyberSourceDefaults.CustomerTokenAddRouteName)'">@T("Common.AddNew")</button>
        </div>
    </div>
</div>

Nop.Plugin.Payments.CyberSource/Views/CustomerToken/TokenAdd.cshtml
@model CustomerTokenEditModel

@{
    Layout = "_ColumnsTwo";
    NopHtml.AddTitleParts(T("Plugins.Payments.CyberSource.PaymentTokens").Text);
    NopHtml.AppendPageCssClassParts("html-account-page");
}

@section left
{
    @(await Component.InvokeAsync("CustomerNavigation", new { selectedTabId = CyberSourceDefaults.CustomerTokensMenuTab }))
}

<form asp-route="@CyberSourceDefaults.CustomerTokenAddRouteName" method="post">
    <div class="page account-page address-edit-page">
        <div class="page-title">
            <h1>@T("Account.MyAccount") - @T("Plugins.Payments.CyberSource.PaymentTokens.AddNew")</h1>
        </div>
        <div class="page-body">
            <div asp-validation-summary="ModelOnly" class="message-error"></div>
            @{
                var dataDictAddress = new ViewDataDictionary(ViewData);
                dataDictAddress.TemplateInfo.HtmlFieldPrefix = "CustomerToken";
                @await Html.PartialAsync("~/Plugins/Payments.CyberSource/Views/CustomerToken/_CreateOrUpdateToken.cshtml", Model.CustomerToken, dataDictAddress)
            }
            <div class="buttons">
                <button type="submit" class="button-1 save-address-button">@T("Common.Save")</button>
            </div>
        </div>
    </div>
</form>

Nop.Plugin.Payments.CyberSource/Views/CustomerToken/TokenEdit.cshtml
@model CustomerTokenEditModel

@{
    Layout = "_ColumnsTwo";
    NopHtml.AddTitleParts(T("Plugins.Payments.CyberSource.PaymentTokens").Text);
    NopHtml.AppendPageCssClassParts("html-account-page");
}

@section left
{
    @(await Component.InvokeAsync("CustomerNavigation", new { selectedTabId = CyberSourceDefaults.CustomerTokensMenuTab }))
}

<form asp-route="@CyberSourceDefaults.CustomerTokenEditRouteName" method="post">
    <div class="page account-page address-edit-page">
        <div class="page-title">
            <h1>@T("Account.MyAccount") - @T("Plugins.Payments.CyberSource.PaymentTokens.Edit")</h1>
        </div>
        <div class="page-body">
            <div asp-validation-summary="ModelOnly" class="message-error"></div>
            @{
                var dataDictAddress = new ViewDataDictionary(ViewData);
                dataDictAddress.TemplateInfo.HtmlFieldPrefix = "CustomerToken";
                @await Html.PartialAsync("~/Plugins/Payments.CyberSource/Views/CustomerToken/_CreateOrUpdateToken.cshtml", Model.CustomerToken, dataDictAddress)
            }
            <div class="buttons">
                <button type="submit" class="button-1 save-address-button">@T("Common.Save")</button>
            </div>
        </div>
    </div>
</form>

Nop.Plugin.Payments.CyberSource/Views/CustomerToken/_CreateOrUpdateToken.cshtml
@model CustomerTokenModel

<input class="token-id" asp-for="Id" type="hidden" />
<div class="edit-address">
    <div class="inputs">
        <label asp-for="CardNumber" asp-postfix=":"></label>
        <input type="text" class="card-number" asp-for="CardNumber" autocomplete="off" maxlength="22" />
        <nop-required />
        <span asp-validation-for="CardNumber"></span>
    </div>
    <div class="inputs">
        <label asp-for="ExpireMonth" asp-postfix=":"></label>
        <select asp-for="ExpireMonth" asp-items="Model.ExpireMonths" style="width:65px;"></select>
        <select asp-for="ExpireYear" asp-items="Model.ExpireYears" style="width:100px;"></select>
        <span asp-validation-for="ExpireMonth"></span>
        <span asp-validation-for="ExpireYear"></span>
    </div>
</div>

<script asp-location="Footer">
    $(document).ready(function() {
        makeCardNumberReadOnly();
    });

    function makeCardNumberReadOnly() {
        if ($('.token-id').val() != 0) {
            $('.card-number').attr('disabled', true);
        }
    }
</script>